(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ac-auto-start 2 nil nil "Customized with use-package auto-complete")
 '(ac-ignore-case nil nil nil "Customized with use-package auto-complete")
 '(ac-trigger-key "TAB")
 '(add-log-always-start-new-record t)
 '(ansi-color-faces-vector
   [default default default italic underline success warning error])
 '(ansi-color-names-vector
   ["black" "#d55e00" "#009e73" "#f8ec59" "#0072b2" "#cc79a7" "#56b4e9" "white"])
 '(backup-by-copying t)
 '(blink-cursor-mode nil)
 '(bmkp-last-as-first-bookmark-file "~/.emacs.d/bookmarks")
 '(c-basic-offset 4)
 '(change-log-default-name "SourceCtrlLog")
 '(column-number-mode t)
 '(comint-buffer-maximum-size 20000)
 '(comint-completion-addsuffix t)
 '(comint-get-old-input (lambda nil "") t)
 '(comint-input-ignoredups t)
 '(comint-input-ring-size 5000)
 '(comint-move-point-for-output nil)
 '(comint-prompt-read-only nil)
 '(comint-scroll-show-maximum-output t)
 '(comint-scroll-to-bottom-on-input t)
 '(cperl-close-paren-offset -4)
 '(cperl-continued-statement-offset 2)
 '(cperl-indent-level 4)
 '(cperl-indent-parens-as-block t)
 '(cperl-tab-always-indent t)
 '(custom-enabled-themes '(tomorrow-night-bright))
 '(custom-safe-themes
   '("6a18a817e5a1d220a8de8af5d6e5f4619fe3df61dd2cbc37b9acd8d77d42e026" "f5519676e9580060b510012ffde3b41dd5392a3debc98a2b02995499a086a7d4" default))
 '(ediff-split-window-function 'split-window-horizontally)
 '(ediff-window-setup-function 'ediff-setup-windows-plain)
 '(exordium-backup-files t)
 '(exordium-delete-trailing-whitespace nil)
 '(exordium-enable-y-or-n t)
 '(exordium-global-git-gutter-mode t)
 '(exordium-highlight-linum t)
 '(explicit-shell-file-name nil)
 '(filesets-data nil)
 '(flycheck-keymap-prefix "\3f")
 '(fringe-mode 16 nil (fringe))
 '(global-auto-revert-mode t)
 '(global-visual-line-mode nil)
 '(helm-ag-insert-at-point 'symbol nil nil "Customized with use-package helm-ag")
 '(helm-buffer-details-flag nil nil nil "Customized with use-package helm")
 '(helm-describe-function-function #'helpful-function nil nil "Customized with use-package helm")
 '(helm-describe-variable-function #'helpful-variable nil nil "Customized with use-package helm")
 '(helm-split-window-default-side 'other nil nil "Customized with use-package helm")
 '(imenu-max-item-length nil)
 '(imenu-sort-function 'imenu--sort-by-name)
 '(kept-new-versions 6)
 '(kill-whole-line t)
 '(line-move-visual nil)
 '(markdown-command "markdown_py")
 '(nyan-animate-nyancat t)
 '(nyan-mode t)
 '(org-support-shift-select t)
 '(package-selected-packages
   '(ws-butler pyvenv virtualenvwrapper groovy-mode all-the-icons evil default-text-scale modern-cpp-font-lock eval-sexp-fu highlight vlf nlinum powerline ox-gfm org-bullets page-break-lines treemacs-projectile goto-chg exec-path-from-shell fill-column-indicator enh-ruby-mode impatient-mode markdown-mode cmake-mode helm-projectile projectile ido-completing-read+ helm-ag helm-swoop helm-flycheck helm-descbinds rainbow-delimiters paredit cider iedit ac-js2 js2-mode yasnippet auto-complete-c-headers helm-rtags flycheck-rtags company-rtags ac-rtags rtags company auto-complete expand-region git-gutter-fringe git-gutter git-timemachine magit highlight-symbol diminish))
 '(protect-buffer-bury-p nil)
 '(python-shell-exec-path '("/opt/bb/bin"))
 '(python-shell-interpreter "python3.8")
 '(save-place-mode t)
 '(show-paren-mode t)
 '(show-trailing-whitespace t)
 '(tool-bar-mode nil)
 '(track-eol t)
 '(treemacs-git-mode nil)
 '(truncate-lines t)
 '(version-control t)
 '(word-wrap nil))
;;;;; '(make-backup-files t)
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(cperl-array-face ((t (:foreground "yellow" :weight bold))))
 '(cperl-hash-face ((t (:foreground "Red" :slant italic :weight bold))))
 '(cursor ((t (:background "spring green"))))
 '(ediff-even-diff-A ((t (:foreground "#969896" :inverse-video nil))))
 '(ediff-even-diff-B ((t (:foreground "#969896" :inverse-video nil))))
 '(linum-highlight-face ((t (:background "white smoke" :distant-foreground "black")))))
;;; If we are running (not just displaying) the emacs process on a mac, we may
;;; want to set the default custom face to height 140.
